In [1]:
import numpy as np


# Creating numpy arrays


In [2]:
print(np.__version__)
arr = np.array([1, 2, 4, 5, 3])
arr1 = np.array(range(1, 11))
print(arr, arr1)


2.3.5
[1 2 4 5 3] [ 1  2  3  4  5  6  7  8  9 10]


# Creating 2D arrays


In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([range(1, 10), range(11, 20), range(21, 30)])
print(a)
print("\n")
print(b)


[[1 2 3]
 [4 5 6]]


[[ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]
 [21 22 23 24 25 26 27 28 29]]


# Array full of ZEROS

In [4]:
a = np.zeros(5)
print(a)
b = np.zeros([5, 5])
print(b)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Array full of ones


In [6]:
a = np.ones(5)
print(a)
b = np.ones([5, 5])
print(b)


[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Array full of ANY number


In [8]:
a = np.full((2, 2), 3)
print(a)


[[3 3]
 [3 3]]


# Identity matrix


In [9]:
a = np.eye(7)
print(a)


[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


# arange() {like range()}


In [10]:
a = np.arange(1, 10).reshape(3, 3)  # <----- .reshape is used to shape the array
print(a)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


# linspace


In [11]:
a = np.linspace(1, 2, 4).reshape(2, 2)
print(a)


[[1.         1.33333333]
 [1.66666667 2.        ]]


# **_CHECKING ARRAY PROPERTIES_**

In [13]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

### shape : used to identify the numbers of rows and column a array have

In [14]:
arr.shape

(2, 3)

### size : used to get total number of element in an array

In [15]:
arr.size

6

### ndim : used to get dimensions of the array

In [16]:
arr.ndim

2

### dtype : used to get the datatype of the elements inside the array

In [17]:
arr.dtype

dtype('int64')

# **_Changing the data types_**

In [18]:
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.dtype)

float32


### astype  is used to change the datatype of an  existing array

In [19]:
arr_int = arr.astype(np.int32)
print(arr_int)

[1 2 3]


# **_Reshaping and Flattening Arrays_**

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [21]:
reshaped = arr.reshape((3, 2))
# Change shape
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
reshaped.shape

(3, 2)

### flatten is used to convert an array into 1D.

In [23]:
flattened = arr.flatten()
print(flattened)

[1 2 3 4 5 6]


In [26]:
print(flattened.shape)
flattened.ndim

(6,)


1