In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
flat[::2] #Every second element

array([ 1,  3,  5,  7,  9, 11])

# _**Slicing returns a view, not a copy! Changes affect the original array.**_

This might seem counterintuitive since Python lists create copies when sliced. But
in NumPy, slicing returns a view of the original array. Both the sliced array and the
original array share the same data in memory, so changes in the slice affect the
original array.

In [6]:
a = flat[3:7]

In [7]:
a

array([4, 5, 6, 7])

In [8]:
a[0] = 67

In [9]:
a

array([67,  5,  6,  7])

In [10]:
flat

array([ 1,  2,  3, 67,  5,  6,  7,  8,  9, 10, 11, 12])

### here when i changed a but flat also change because slicing returns a view ,copy not a copy!

## Use .copy() if you need an independent copy.

In [11]:
b = flat[3:9].copy()

In [12]:
print(b)
flat

[67  5  6  7  8  9]


array([ 1,  2,  3, 67,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
b[0] = 943

In [14]:
print(b)
flat

[943   5   6   7   8   9]


array([ 1,  2,  3, 67,  5,  6,  7,  8,  9, 10, 11, 12])

Not changed because of .copy()

# _**Fancy Indexing & Boolean Masking**_

# ------------------------------------------------------------------------

In [15]:
# Fancy Indexing : select multiple element using index
ar = np.array([1,2,3,4,5,6,7,8,32,132,3,234,34])

print(ar[[1,3,6,8]])

[ 2  4  7 32]


In [16]:
# Boolean Masking : filter data by condition
print(ar[ar>10])

[ 32 132 234  34]


# _**Exercises for Practice**_

# ------------------------------------------------------------------------

- Create a 3×3 array filled with random numbers and print its shape.
- Convert an array of floats [1.1, 2.2, 3.3] into integers.
- Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6] .
- Reshape a 1D array of size 9 into a 3×3 matrix.
- Use boolean masking to filter numbers greater than 50 in an array.

In [17]:
import random

In [18]:
arr1 = np.random.randint(100,size= (3,3))

In [19]:
arr1

array([[19, 50, 98],
       [99, 67, 77],
       [57, 92, 86]])

In [20]:
arr1.shape

(3, 3)

In [21]:
arr2 = np.array([ [1.1, 2.2, 3.3] ])
print(arr2.dtype)
arr2.astype('int32')

float64


array([[1, 2, 3]], dtype=int32)

In [22]:
d = np.array([1, 2, 3, 4, 5, 6])
print(d[[1,3,5]])
# print(d[d%2 ==0])

[2 4 6]


In [23]:
e = np.arange(1,10)
print(e)
e = e.reshape(3,3)
print(e)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
flat = arr1.flatten()
print(flat[flat > 50])

[98 99 67 77 57 92 86]
