# _**Multidimensional Indexing and Axis**_

- 1D array → 1 axis (axis 0)
- 2D array → 2 axes (axis 0 = rows, axis 1 = columns)
- 3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

In [1]:
import numpy as np

### Axes in 2D array

In [2]:
arr = np.arange(1,10).reshape(3,3)

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print(np.sum(arr, axis=0)) #<----------- axis = 0 -> add all rows 

[12 15 18]


In [5]:
print(np.sum(arr[:,0:2] ,axis = 1)) #<----- axis = 1 -> with slicing means add only columnn 0 and 1

[ 3  9 15]


In [7]:
a = np.sum(arr[0:2,0:2] ,axis = 1).reshape(2,1)
print(a)

[[3]
 [9]]


### Indexing in Multidimensional Arrays 

In [10]:
print(arr[1,1]) # Row index = 1 , Column index = 1 --> Output = 5

5


In [16]:
print(arr[1:3 , 0:2]) # Extracts first 2 rows and last 2 columns

[[4 5]
 [7 8]]


## Indexing in 3D Arrays
-- For 3D arrays, the first index refers to the “depth” (sheets of data).

In [19]:
arr3D =  np.arange(1,13).reshape(2,2,3)
print(arr3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Accessing elements in 3D array

In [31]:
print(arr3D[1,0,1]) # the depth is 1 , row is 0 , column is 1 -->> Output is 8
print(arr3D[0,1,2]) # the depth is 0 , row is 1 , column is 2 -->> Output is 6
print(arr3D[:,0]) # Get all first row 
print(arr3D[:,0:,1:]) # get all the columns expect 1st(index=0)


8
6
[[1 2 3]
 [7 8 9]]
[[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]


- : → take all matrices

- 0 → take row 0 from each matrix

- No third index → take all columns of that row


## Changing Data Along an Axis

In [32]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
arr3D[:,0,1] = 000 # depth - :"All selected" , row = 0 , column = 1 -- 2,8 =>> 0,0
print(arr3D)

[[[ 1  0  3]
  [ 4  5  6]]

 [[ 7  0  9]
  [10 11 12]]]
