# _**Built in Mathematical Functions in NumPy**_

Here are some common NumPy methods that are frequently used for statistical and mathematical operations:

1. np.mean() – Compute the mean (average) of an array.
    np.mean(arr)
2. np.std() – Compute the standard deviation of an array.
    np.std(arr)
3. np.var() – Compute the variance of an array.
    np.var(arr)
4. np.min() – Compute the minimum value of an array.
    np.min(arr)
5. np.max() – Compute the maximum value of an array.
    np.max(arr)
6. np.sum() – Compute the sum of all elements in an array.
    np.sum(arr)
7. np.prod() – Compute the product of all elements in an array.
    np.prod(arr)
8. np.median() – Compute the median of an array.
    np.median(arr)
9. np.percentile() – Compute the percentile of an array.
    np.percentile(arr, 50)
#### For the 50th percentile (median)
10. np.argmin() – Return the index of the minimum value in an array.
    np.argmin(arr)
11. np.argmax() – Return the index of the maximum value in an array.
    np.argmax(arr)
12. np.corrcoef() – Compute the correlation coefficient matrix of two arrays.
    np.corrcoef(arr1, arr2)
13. np.unique() – Find the unique elements of an array.
    np.unique(arr)
14. np.diff() – Compute the n-th differences of an array.
    np.diff(arr)
15. np.cumsum() – Compute the cumulative sum of an array.
    np.cumsum(arr)
16. np.linspace() – Create an array with evenly spaced numbers over a specified interval.
    np.linspace(0, 10, 5)
#### 5 numbers from 0 to 10
17. np.log() – Compute the natural logarithm of an array.
    np.log(arr)
18. np.exp() – Compute the exponential of an array.
    np.exp(arr)

In [1]:
import numpy as np

In [3]:
arr = np.array([1,42,34,32,43,1,42])

In [4]:
np.mean(arr)

np.float64(27.857142857142858)

In [5]:
np.std(arr)

np.float64(17.43091319162245)

In [6]:
np.var(arr)

np.float64(303.8367346938776)

In [7]:
np.min(arr)

np.int64(1)

In [8]:
np.max(arr)

np.int64(43)

In [9]:
np.sum(arr)

np.int64(195)

In [11]:
np.prod(arr)

np.int64(82526976)

In [12]:
np.median(arr)

np.float64(34.0)

In [14]:
np.percentile(arr,50)

np.float64(34.0)

In [15]:
np.argmin(arr)

np.int64(0)

In [16]:
np.argmax(arr)

np.int64(4)

In [17]:
np.corrcoef(arr)

np.float64(1.0)

In [18]:
np.unique(arr)

array([ 1, 32, 34, 42, 43])

In [19]:
np.diff(arr)

array([ 41,  -8,  -2,  11, -42,  41])

In [20]:
np.cumsum(arr)

array([  1,  43,  77, 109, 152, 153, 195])

In [32]:
np.linspace(2,10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [33]:
np.log(arr)

array([0.        , 3.73766962, 3.52636052, 3.4657359 , 3.76120012,
       0.        , 3.73766962])

In [34]:
np.exp(arr)

array([2.71828183e+00, 1.73927494e+18, 5.83461743e+14, 7.89629602e+13,
       4.72783947e+18, 2.71828183e+00, 1.73927494e+18])